//example of questions generated by script

var scenes = {};
var names = [ 'Alex' , 'Sarah' , 'Michael', 'Paul', 'Joe', 'John'];
var reasons = ["chest pain", "sinuses", "gastrointestinal", "other"];
var chestReasons = ['cough', 'shortness of breath', 'blood in sputum', 'chest discomfort', 'additional'];
var giReasons = ['constipation', 'diarrhoea', 'abdominal pain', 'vomiting', 'heartburn'];
scenes.welcome = {};

scenes.welcome.start = [
    { text: "Hello, I am your virtual Doctor. Can I get your name?" },
];

names.forEach(function(name) {
    scenes.welcome[name] = [{text: "Hello " + name + "," + "What is the main reason for your visit today?"}];
});

reasons.forEach(function(reason) {
    scenes.welcome[reason] = [{text: "You are here because of " + reason}];
});

chestReasons.forEach(function(reason) {
    scenes.welcome[reason] = [{text: "You having an issue with " + reason}];
});

giReasons.forEach(function(reason) {
    scenes.welcome[reason] = [{text: "You are having problems with " + reason}];
});

scenes.welcome.noMatch = [
    { text: "Sorry that answer has no match, can you try again?" },
];

scenes.welcome.noReasonMatch = [
    { text: "Sorry that reason was not a match, can you please try again?" },
];

scenes.welcome.noChestMatch = [
    { text: "Sorry I must of miss heard you, can you tell me again what was wrong with your chest?" },
];

scenes.welcome.noGiMatch = [
    { text: "Please try again? I didn't catch that" },
];

scenes.welcome.no = [
    { text: "You have no further issues" },
];

scenes.welcome.next = [
    { text: "You have no further issues with your chest" },
];

scenes.welcome.not = [
    { text: "You have no other gastrointestinal problems" },
];
scenes.welcome.mild = [
    { text: "Your session with me is over. Your details have been sent, monitor your symptoms over the next 24 hours and someone will call you in the next 24 hours. If you feel we have not met your needs or assessed you fully please contact the staff. Have a good day"},
];

scenes.welcome.moderate = [
    { text: "Your session with me is over. Your details have been sent, Someone will call you in the next 24 hours. If you feel we have not met your needs or assessed you fully please contact the staff. Thank you for your visit today"},
];

scenes.welcome.severe = [
    { text: "Your session with me is over. Your details have been sent, Someone will call you as early as possible. If you feel we have not met your needs or assessed you fully please contact the staff."},
];

scenes.welcome.urgent = [
    { text: "Your session with me is over. Your details have been sent, please call the team as soon as possible."},
];

script = ["welcome"];

module.exports = { script: script, scenes: scenes };